introduce linters
yktt-nuane/shiftmaking pull request #45
Opened 2022-12-10 07:49 UTC by yktt-nuane

## Describe the PR

To close #2 

The relevant Issue must be specified.
Then explain **why** you implemented it this way for that.

## Screenshots

None

## Detail of the change

A clear and concise description of what you changed.

- [ ] introduce Prittier
- [ ] introduce Stylelint
- [ ] introduce Eslint
- [ ] introduce Husky

## Anticipated impacts

None

## To reproduce

Steps to check the behavior:

1. `npm run format`
2. `git add .`
3. `git commit -m ""`

## Appendix

None

2022-12-11 02:48 UTC, shin-sforzando commented
The relevant Issue must be specified.
Then explain why you implemented it this way for that.
は、章に対する説明文なので消してください。

2022-12-11 03:15 UTC, yktt-nuane commented
消去しました。

2022-12-11 03:49 UTC, shin-sforzando requested changes
これを2コミットでやってるのがおかしいですね。
ESLint入れた瞬間、Prettier入れた瞬間、Stylelint入れた瞬間、って分けてないからタイムマシンとして全く使えない。

2022-12-11 03:49 UTC, shin-sforzando commented on package.json
> -    "lint": "next lint"
このコマンドにあるように、今のNext.jsはデフォルトでESLint入ってるので個別に入れ直すのは悪手ですね。
https://nextjs.org/docs/basic-features/eslint

2022-12-11 03:49 UTC, shin-sforzando commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
prettierの `--check` は単独で使わないと意味がないのでは？

2022-12-11 03:49 UTC, shin-sforzando commented on .prettierrc.json
> +{}
prettierの設定ファイルが複数存在するのは無駄ですね。

2022-12-11 03:49 UTC, shin-sforzando commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint"
Typo多いのでSpellCheck系も入れましょう。

2022-12-11 03:49 UTC, shin-sforzando commented on .vscode/settings.json
> +      "editor.defaultFormatter": "esbenp.prettier-vscode"
個別にデフォルトフォーマッタを設定するなら、全体のデフォルトフォーマッタを決めてから、その差分だけ記述する方がスッキリするのでは。

2022-12-11 03:49 UTC, shin-sforzando commented on README.md
>  ## Prerequisites
ここも更新必要では？

2022-12-11 03:49 UTC, shin-sforzando commented on package.json
> +    "eslint:fix": "eslint src --ext .js,jsx,.ts,.tsx --fix",
慣例ですけど `:` はオプション的な意味合いで使うので、
`eslint` ってscriptがあって `eslint:fix` があるならわかるんですけど、一個しかないなら `eslint` で良いんじゃないの？って思いました。

2022-12-11 03:49 UTC, shin-sforzando commented on package.json
> +    "eslint:fix": "eslint src --ext .js,jsx,.ts,.tsx --fix",
ちなみに `npm run` は `--` を挟んで引数を後から増やせます。
cf. https://docs.npmjs.com/cli/v9/commands/npm-run-script
「毎回fixしたいとは限らんな」って時は `--fix` 抜きで定義しておいてfixしたい実行時には `npm run eslint -- --fix` とする運用もありです。

2022-12-11 03:49 UTC, shin-sforzando commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
これだと `.nuxt` の中身などもprettierかかりませんか？

2022-12-11 03:49 UTC, shin-sforzando commented on package.json
> +    "eslint-plugin-simple-import-sort": "^8.0.0",
`eslint-plugin-import` でもインポートオーダーの設定できるはず。
cf. https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

2022-12-11 03:49 UTC, shin-sforzando commented on stylelint.config.js
> +  ],
`stylelint-prettier` を使わないなら `package.json` から消してそもそもインストールしないようにしましょう。
他にも不要にインストールしてるパッケージがないかチェックしてください。

2022-12-11 04:03 UTC, shin-sforzando commented
> 消去しました。

言わなくても伝わるかなと思って割愛してしまいましたが
A clear and concise description of what you changed.
もコメントです。

2022-12-11 04:05 UTC, shin-sforzando commented
`- [x]` とするとチェックボックスにチェックが入ります。
PR bodyにあるチェックボックスに全てチェックが入ってないなら「まだ終わってないみたいだからレビューしなくて良いな」と伝えてることになります。

2022-12-11 04:05 UTC, yktt-nuane commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint"
Code Spell Checkerを入れるので良いでしょうか？
cf. https://qiita.com/diescake/items/98c5a099e85775cd917d

2022-12-11 04:06 UTC, shin-sforzando commented
> introduce Eslint

Typoです。ESLintが正式名称です。
https://eslint.org

2022-12-11 04:07 UTC, yktt-nuane commented on .prettierrc.json
> +{}
[.prettierrc.json](https://github.com/yktt-nuane/shiftmaking/pull/45/files/2542dfd640ed0632fabdbc88f68e58d8d0cef789#diff-979a4a52db5287c891eac28a141bfa97bf8b0732ed5afae848d90956ef80e78d)を削除します。

2022-12-11 04:17 UTC, yktt-nuane commented on .vscode/settings.json
> +      "editor.defaultFormatter": "esbenp.prettier-vscode"
むしろ、全体のデフォルトフォーマッタで足りるので、記述を変更しようと思います。

2022-12-11 04:22 UTC, yktt-nuane commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
`--check --write` でも `--check`は動くのでいいと思いました。
`--check`と`--write`を別にした方が良い理由はありますか？

2022-12-11 04:27 UTC, yktt-nuane commented on package.json
> +    "eslint:fix": "eslint src --ext .js,jsx,.ts,.tsx --fix",
> このコマンドにあるように、今のNext.jsはデフォルトでESLint入ってるので個別に入れ直すのは悪手ですね。

`"eslint:fix": "eslint src --ext .js,jsx,.ts,.tsx --fix"`を`"lint": "next lint --dir src"`に変更して、"lint:fix": "npm run lint --fix"に変更するのは、どうでしょうか？

2022-12-11 04:29 UTC, yktt-nuane commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
かかります。
理解不足で申し訳ありませんが、`.next`にはprettierが掛からない方が良いですか？

2022-12-11 04:30 UTC, yktt-nuane commented on stylelint.config.js
> +  ],
`stylelint-config-prettier`を削除します。
注意してチェックします。

2022-12-11 04:32 UTC, yktt-nuane commented
> これだとレビュアーの無駄なコミットが入ってしまいますし、
> すでにきちんとフォーマットされてるならば add . で何も追加されず、すなわちコミットもできないのでは？

GitHookが機能するかをチェックしてもらうには、どのようにするのでしょうか？

2022-12-11 07:07 UTC, shin-sforzando commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
https://prettier.io/docs/en/cli.html#--check に"When you want to check if your files are formatted, you can run Prettier with the --check flag (or -c). This will output a human-friendly message and a list of unformatted files,"とある通り、フォーマットされてるかチェックして人間にとって可読性の高い結果を得たいときに使うのが `--check` ですよね。
対して、 `--write` は自動で直せるものは勝手に直せ、というオプションです。
子供に「人にはわかりやすく説明して欲しいけど、自分で勝手にお話変えて良いからね」って言ってるようなもんです。
意味ないですよね。自分で直したい気分の時は `--check` 使うし、勝手によろしくやっといて欲しい気分なら `--write` 使う、そのためにそれぞれ `prettier:check` `prettier:write` 用意しとく、なら話はわかります。

2022-12-11 07:14 UTC, shin-sforzando commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
> でも --checkは動くのでいいと思いました。
考え方がおかしくて、それなら `--loglevel log` `--cache-location ./node_modules/.cache/prettier/.prettier-cache` をつけたって動きます。
CLIしかりプログラムしかり、「書かなくても動くから良い」ならわかりますが、「書いても動くので良い」なら、なんで `--loglevel log` `--cache-location ./node_modules/.cache/prettier/.prettier-cache` を書かないんですか？って話になります。
いっぱい書きたいならReactとかNext.jsなんて便利フレームワーク使わない方がいっぱい書けてハッピーです。
プログラマは「書きたくない」からフレームワーク作ったりライブラリ作ったりして進化してるんです。

2022-12-11 07:15 UTC, yktt-nuane commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
ありがとうございます。分かりやすく、納得しました。
`--check`は`prettier:check`として、別で用意する事にします。

2022-12-11 07:18 UTC, shin-sforzando commented on prettier.config.js
> +  singleQuote: false,
ちなみに、Next.jsのチュートリアルやった時に気付いたと思うんですが、
https://nextjs.org/docs/basic-features/pages
Next.js界隈は行末セミコロン無し、ダブルクォートよりシングルクォートの文化ですね。
これも「書かない」でデフォルトに任せておけば勝手にそう揃ってたはず。

2022-12-11 07:21 UTC, shin-sforzando commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint"
> 入れれます。

とTypoぶっ込んでくるの、さすが横山さん、狙ってやってますね？
ちなみに日本語のLintはこの辺が有名です。 https://github.com/textlint-ja/textlint-ja
（導入すべきかはお任せしますが）

2022-12-11 07:24 UTC, shin-sforzando commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
https://nextjs.org/docs/deployment
`.next` は本番デプロイ用にサイズ最適化したファイル群などが入ってきますので、フォーマットしたらサイズ微増しますし、ここを人間が読みにいく場面はないのにその整形に時間取られるのは無駄です。

2022-12-11 07:28 UTC, shin-sforzando commented on stylelint.config.js
> +  ],
え、そっちを消すの？
https://github.com/prettier/stylelint-prettier
もう1年以上開発が止まってる上にREADME.mdにも「stylelint-config-prettierでもできるよ」って言及してるのに。

2022-12-11 07:32 UTC, shin-sforzando commented
> > これだとレビュアーの無駄なコミットが入ってしまいますし、
> > すでにきちんとフォーマットされてるならば add . で何も追加されず、すなわちコミットもできないのでは？
> 
> Huskyが機能するかをチェックしてもらうには、どのようにするのでしょうか？

ググったらすぐ出てきました。
https://github.com/typicode/husky/issues/446

または `git commit --dry-run` でも出来そうですね。

2022-12-11 07:33 UTC, shin-sforzando commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
人手で直す場面ないと思うけどなぁ。

2022-12-11 07:36 UTC, yktt-nuane commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
ないですね。`--check`はなしにします。

2022-12-11 07:39 UTC, yktt-nuane commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint"
結構必死です。

2022-12-11 07:40 UTC, yktt-nuane commented on package.json
> +    "prettier:fix": "prettier --check --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'",
承知致しました。

2022-12-11 07:46 UTC, yktt-nuane commented on prettier.config.js
> +  singleQuote: false,
> Next.js界隈は行末セミコロン無し、ダブルクォートよりシングルクォートの文化ですね。
> これも「書かない」でデフォルトに任せておけば勝手にそう揃ってたはず。

「行末セミコロン無し」「シングルクォート」に変更します。

2022-12-11 12:29 UTC, yktt-nuane commented
> > > これだとレビュアーの無駄なコミットが入ってしまいますし、
> > > すでにきちんとフォーマットされてるならば add . で何も追加されず、すなわちコミットもできないのでは？
> > 
> > 
> > Huskyが機能するかをチェックしてもらうには、どのようにするのでしょうか？
> 
> ググったらすぐ出てきました。 [typicode/husky#446](https://github.com/typicode/husky/issues/446)
> 
> または `git commit --dry-run` でも出来そうですね。

これの実装が、どっちも分かりません...`git commit --dry-run`でHuskyが動かないのが、エラーか自分が悪いのか...

2022-12-11 14:52 UTC, shin-sforzando commented
> これの実装が、どっちも分かりません...`git commit --dry-run`でHuskyが動かないのが、エラーか自分が悪いのか...

自分も試してみましたが、 `--dry-run` だとhooksが呼ばれないみたいですね。
https://tech.yappli.io/entry/husky_codereading
をみて、

```shell
$ git config -l | grep hooks
core.hookspath=.husky
$ ./.husky/pre-commit
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
```

で確認できました。

2022-12-12 02:04 UTC, shin-sforzando requested changes
相変わらず `.next` にPrettier効いてません？

2022-12-12 02:04 UTC, shin-sforzando commented on prettier.config.js
> +  quoteProps: "as-needed",
"as-needed"がデフォルトなので書かなくて良いですね。
書かなくて動くなら書かない方が良い、です。
他のパラメータもデフォルト値を設定してないか確認してみてください。

2022-12-12 02:04 UTC, shin-sforzando commented on src/pages/index.tsx
> +import styles from '../styles/Home.module.css'
相対パスじゃなくて絶対パスで参照できるようにした方が良いですよ。
cf. https://nextjs.org/docs/advanced-features/module-path-aliases

2022-12-12 02:04 UTC, shin-sforzando commented on next.config.js
> +};
`semi: false` 効いてないみたいね。

2022-12-12 04:29 UTC, yktt-nuane commented on src/pages/index.tsx
> +import styles from '../styles/Home.module.css'
tsconfig.jsonで`"baseUrl": "src"`に設定してあるので絶対パス参照できるようになっていると思います。該当コードを書き換えました。

2022-12-12 06:24 UTC, shin-sforzando requested changes

2022-12-12 06:24 UTC, shin-sforzando commented on .prettierignore
> +/.next/
行末に改行がないようですね。
https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html#toc5

それから、公式Docを読んでこの設定を施してると思うんですが、
https://prettier.io/docs/en/ignore.html
`.prettierignore` があると、逆にデフォルトで無視していた `.git` `node_modules` が無視されなくなる場合があります（環境依存）。
もちろん、 `.git` `node_modules` はどんな環境でもPrettierして欲しくないので `.prettierignore` に念の為加えておくと良いでしょう。

2022-12-12 06:24 UTC, shin-sforzando commented on README.md
> +  - Stylelint (version 14)
Versionによって挙動が変わらなそうなライブラリについては別に書かなくて良いと思いますし、
逆に、NodeやNextはマイナーバージョンでも挙動が変わるのでメジャーバージョンだけでは足りないと思います。
基本的に後方互換性は保たれるはずなので、 `Python 3.9.11 or higher` みたいに「〜以上」という書き方をよく見ます。

2022-12-12 06:24 UTC, shin-sforzando commented on package.json
> +    "format": "npm run lint && npm run stylelint && npm run prettier"
あれ、公式に沿ってHusky入れたら `prepare` っての増えませんか？
https://typicode.github.io/husky/#/?id=install

2022-12-12 06:24 UTC, shin-sforzando commented on package.json
> +    }
で、逆にこの書き方はHuskyの古い書き方だと思うけどな。
https://typicode.github.io/husky/#/?id=husky-4-to-8-cli

2022-12-12 06:24 UTC, shin-sforzando commented on src/pages/index.tsx
> +import styles from 'styles/Home.module.css'
依然、相対パスですね。Path Aliasを設定したら `@` が使えるようになります。

2022-12-12 10:41 UTC, shin-sforzando requested changes
行末に改行が入ってなかった件、僕も調べてみたんですがPrettierにそういう設定はないんですね。
https://github.com/prettier/prettier/issues/6360#issuecomment-518994475

VSCodeでも設定できますが、
https://qiita.com/kyo_nanba/items/d384b2a46170bf8764dd
弊社ではもっぱらEditorconfigを使ってます。

```.editorconfig
# editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[Makefile]
indent_style = tab

[*.md]
trim_trailing_whitespace = false
```

2022-12-12 10:41 UTC, shin-sforzando commented on package.json
> +    }
ここ、古い書き方です。 `.husky` に同じ内容あって、そちらを実行してるので削除して問題ないはず。

2022-12-12 10:41 UTC, shin-sforzando commented on src/pages/_app.tsx
>  import '../styles/globals.css'
ここも相対パス残ってます。

2022-12-12 10:41 UTC, shin-sforzando commented on tsconfig.json
> +      "@/styles/*": ["styles/*"]
それでも間違ってないんですが、

```suggestion
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
```

こっちの方が `styles` 以外のディレクトリにも使えて便利です。

2022-12-12 11:12 UTC, yktt-nuane commented
今回はsettings.jsonに`"files.insertFinalNewline": true`を追加する形で運用しようと思います。

2022-12-12 12:17 UTC, shin-sforzando requested changes
細かい話が多すぎたのでこちらから修正コミットを送りました。
確認し、理解できないところがあればコメントください。

2022-12-12 12:45 UTC, yktt-nuane commented
これを書けと言われたら、無理ですが、書いてあることを理解する事はできます。
1点質問です。
"format": "prettier --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'"となっているのは、僕がチェックを`npm run format`としているからですか？それとも、関係なく`prettier`ではなく、`format`と設定しますか？

2022-12-12 13:30 UTC, shin-sforzando commented
> これを書けと言われたら、無理ですが、書いてあることを理解する事はできます。 1点質問です。 `"format": "prettier --write './**/*.{js,jsx,ts,tsx,css,scss,md,mdx}'"`となっているのは、僕がチェックを`npm run format`としているからですか？それとも、関係なく`prettier`ではなく、`format`と設定しますか？

良い質問です。2つの意味を含んでいますが。

まず、Formatは整形、Lintは静的解析なので、目的の違うCLIが `&&` でつながっている事に違和感を覚えました。

さらに、 `prettier` と固有名詞を使っているのも違和感でした。
たとえばNext.jsのデフォルト、 `npm run lint` の実態は `next lint` 、さらにその実態はESLintでしたよね。
他も、たとえば `npm run start` の実態はNode HTTP serverです。
Slackでちょっと書いたRomeとか、Linterってこの世にたくさんあるので、
もしかしたら将来ESLintじゃなくなる、Prettierじゃなくなる日が来ても全然おかしくない。
バックエンドサーバも同様。
つまり、ユーザから見たら「とにかくLintしたい！」のであって、何でLintされるかは知らんくて良い、
「とにかくstartしたい！サーバが何かは知らん！」
つまり、 `npm run 動詞` に揃えておけばライブラリ差し替えても困らないよね、ってことです。

よっぽど「E2E、CypressとPlaywright、二つ用意したぜ」みたいな場面なら固有名詞使うかもですが、
それでも `npm run test:e2e:cypress` `npm run test:e2e:playwright` かなぁ。

2022-12-12 13:36 UTC, yktt-nuane commented
納得です！

2022-12-12 18:03 UTC, shin-sforzando approved these changes

2022-12-12 18:04 UTC, shin-sforzando commented
納得いただけたようなのでApproveします。
Mergeしてください。

2022-12-13 01:35 UTC, shin-sforzando approved these changes

2022-12-13 01:41 UTC, merged