prepare a way to manage confidential information
yktt-nuane/shiftmaking pull request #46
Opened 2022-12-13 12:42 UTC by yktt-nuane

## Describe the PR

To close #11 

## Screenshots
None

## Detail of the change

(T. B. D.)

- [x] A
- [ ] B
- [ ] C

## Anticipated impacts

## To reproduce

(T. B. D.)

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Appendix

None

2022-12-13 23:36 UTC, shin-sforzando commented
"Detail of the Change"はACを書くところではなく、その名の通り、「このPRで何を変更したか」です。

2022-12-13 23:42 UTC, shin-sforzando commented
これを使う手順がREADMEにないと新参共同開発者は何もできません。

2022-12-13 23:43 UTC, shin-sforzando commented
Reviewerにgit-secretをインストールさせないと何もできません。
鍵の共有をさせる手順も書かれていません。

2022-12-13 23:44 UTC, shin-sforzando commented
`.env.local` が正しく復号されたらどうなっているべきかわからないので、確認できません。

2022-12-14 00:06 UTC, shin-sforzando commented
秘密にすべきファイルが修正されたとき、更新された状態でコミットされるか、開発者の記憶に任されてます。
pre-commitで強制しましょう。
同様に、pullしたときに必ず復号する仕組みも実装できます。

2022-12-14 01:23 UTC, yktt-nuane commented
> 秘密にすべきファイルが修正されたとき、更新された状態でコミットされるか、開発者の記憶に任されてます。
> pre-commitで強制しましょう。
> 同様に、pullしたときに必ず復号する仕組みも実装できます。

pre-commitに`git-secret-reveal`を実装してみました。もっといいやり方はありそうですが、いかがでしょうか?

2022-12-14 01:50 UTC, shin-sforzando commented
> .env.local file is "This is a secret file."

ってどういう意味ですか？

2022-12-14 02:06 UTC, shin-sforzando requested changes

2022-12-14 02:06 UTC, shin-sforzando commented on README.md
> +
```suggestion
#### Environment Variables

##### `.env.local`

```.env.local
SECRET_KEY=xxxxxxxx
```
```

「このシステムの動作に何が必要か」はREADME.mdに記載したい内容です。
環境変数も「このシステムの動作に必要なもの」です。
どんな環境変数がどこに保存されているかを書きます。
その際、Valueは当然秘匿情報なので `xxxx` 等で伏せ、Keyだけ書きます。

2022-12-14 02:06 UTC, shin-sforzando commented on README.md
> +
そうすると、 `.env.local` が復号された後にどうなっているべきかは "See README.md for details" と書くだけで良くなります。

2022-12-14 02:06 UTC, shin-sforzando commented on README.md
> +    - [Contributors](#contributors)
TOCの更新がされていてとても良いですが、
さて、このTOCを更新したVSCode拡張は `extensions.json` に入ってませんね。

2022-12-14 02:06 UTC, shin-sforzando commented on README.md
> +To hide secret files, `git secret hide`.
`package.json` にせっかくscripts用意してるので、そちらを使わせる方が良いのでは。

2022-12-14 03:29 UTC, yktt-nuane commented
Co-authored-by: Shin'ichiro Suzuki <32637762+shin-sforzando@users.noreply.github.com>
鈴木さんからの変更提案を承認した後の処理が分からず、`git push`できずにいます。差分の処理はどうしたら良いでしょうか？

2022-12-14 03:34 UTC, yktt-nuane commented
ちょっと心配ですが、`git pull origin branch名前`で何とかできた模様です。

2022-12-14 06:07 UTC, shin-sforzando commented
> ちょっと心配ですが、`git pull origin branch名前`で何とかできた模様です。

コメント後のコミット https://github.com/yktt-nuane/shiftmaking/pull/46/commits/a1fc6533267fcfe2be87c985fca6f588beaef06c を見る限り、README.md以外変更されてないように見えますが…

2022-12-14 08:18 UTC, yktt-nuane commented
![image](https://user-images.githubusercontent.com/61369434/207542577-6e68e3e6-8b73-4567-ab96-6d0fad3535d2.png)
一応、全てcommitされていますが、どうでしょうか？

2022-12-14 08:27 UTC, shin-sforzando commented
いや、変更反映されてないですよ？
https://github.com/yktt-nuane/shiftmaking/blob/a1fc6533267fcfe2be87c985fca6f588beaef06c/.gitignore

2022-12-14 09:44 UTC, shin-sforzando commented on README.md
> +SECRET_KEY=xxxxxxxx
これ、前のコメントが途中で壊れてて申し訳ないんですが、
` ``` ` で閉じる必要があります。

2022-12-15 02:03 UTC, shin-sforzando requested changes

2022-12-15 02:03 UTC, shin-sforzando commented on README.md
> +
重複してません？

2022-12-15 04:52 UTC, shin-sforzando approved these changes

2022-12-15 04:55 UTC, merged