prepare unit test framework
yktt-nuane/shiftmaking pull request #47
Opened 2022-12-16 04:31 UTC by yktt-nuane

## Describe the PR

To close #5 

## Screenshots

None

## Detail of the change

(T. B. D.)

- [x] A
- [ ] B
- [ ] C

## Anticipated impacts

None.

## To reproduce

(T. B. D.)

## Appendix

None

2022-12-16 04:38 UTC, shin-sforzando commented
いろいろやってしまう前に先に頭出しなんですけど、Next/Jestは現在進行形で仕様が変わっており、Jestでやるつもりなら↓を一通り見てから進めると良いです。
https://github.com/vercel/next.js/discussions/31152

2022-12-16 05:03 UTC, yktt-nuane commented
なるほど。特にJestに慣れているわけでもなく、使った事もないので、鈴木さんが良い印象を持たれているVitestを導入する方向で進めても良いですか？

2022-12-16 05:28 UTC, shin-sforzando commented
んー、結論、どっちを採用しても良いと思うのですが、こういう「どちらが良いかわからない」状況を自分で解決する能力っていずれ必要だと思うので、「誰かが良いって言ってたから」じゃなくて自身の納得を持って進む練習機会とするといいと思いますよ。

2022-12-16 05:32 UTC, shin-sforzando commented
あわせて、ある時点で「当時の選択は間違っていたな」と潔く諦める力も必要で、
そのために「ある行為で影響を受けた範囲はどれか」みたいなものをきちんと理解しながら進めるのが重要になってきます。
例えば、今回は時間が差し迫っているので納得を得ずにどちらかを選んだとしても、「理解の伴った開発」を意識しておけば未来のある時点でリカバリーしたとしても小ダメージですみます。

2022-12-16 12:03 UTC, shin-sforzando requested changes
`npm install` させてないからReviewerは実行時エラーになると思います。

2022-12-16 12:03 UTC, shin-sforzando commented on package.json
>      "next": "13.0.6",
```suggestion
    "next": "13.0.7",
```

2022-12-16 12:03 UTC, shin-sforzando commented on package.json
>      "@types/node": "18.11.13",
```suggestion
    "@types/node": "18.11.15",
```

2022-12-16 12:03 UTC, shin-sforzando commented on package.json
>      "@typescript-eslint/eslint-plugin": "^5.46.0",
```suggestion
    "@typescript-eslint/eslint-plugin": "^5.46.1",
```

2022-12-16 12:03 UTC, shin-sforzando commented on package.json
>      "@typescript-eslint/parser": "^5.46.0",
```suggestion
    "@typescript-eslint/parser": "^5.46.1",
```

2022-12-16 12:03 UTC, shin-sforzando commented on package.json
>      "eslint-config-next": "13.0.6",
```suggestion
    "eslint-config-next": "13.0.7",
```

2022-12-16 12:09 UTC, shin-sforzando commented
https://vitest.dev/guide/ide.html　このVSCode拡張、どうなんでしょうね。使ったことない。
こっち https://marketplace.visualstudio.com/items?itemName=antfu.vite は使ってて結構便利だなと思うんですが。

2022-12-16 12:26 UTC, yktt-nuane commented on package.json
> +    "react-dom": "18.2.0",
削除します。

2022-12-16 12:33 UTC, yktt-nuane commented on package.json
> +    "eslint": "8.29.0",
`"@vitest/coverage-c8": "^0.25.8"`は、含まれていませんでした。

2022-12-16 14:22 UTC, shin-sforzando requested changes

2022-12-16 14:22 UTC, shin-sforzando commented on package.json
> +    "@types/react-dom": "18.0.9",
`react-dom` を使っていないならそのTypesも不要ですね。

2022-12-16 14:22 UTC, shin-sforzando commented on vitest.config.ts
> +    environment: 'jsdom',
これが何を意味するか、一応理解しておいてくださいね。
https://vitest.dev/config/#environment

2022-12-17 00:34 UTC, yktt-nuane commented on package.json
> +    "eslint": "8.29.0",
`"eslint": "8.29.0"`は元々入っていたのに、なぜか差分として検出されています...

2022-12-17 00:34 UTC, yktt-nuane commented on package.json
> +    "eslint": "8.29.0",
`"eslint": "8.29.0"`は元々入っていたのに、なぜか差分として検出されています...

2022-12-17 00:37 UTC, yktt-nuane commented on package.json
> +    "test:vitest": "vitest --run && vitest run --coverage"
覚えています。`test:unit`でどうでしょうか？

2022-12-17 02:55 UTC, shin-sforzando commented on package.json
> +    "eslint": "8.29.0",
いや、そう言う意味でなく、ESLintはNext.jsの中に含まれてるから、別にインストールする必要がないってことです。
試しにこの行を消して `npm install` しなおしてから `npm run lint` できるか試してみてください。

2022-12-17 03:17 UTC, yktt-nuane commented on package.json
> +    "eslint": "8.29.0",
確認しました。不要ですね。削除します。

2022-12-17 04:40 UTC, shin-sforzando requested changes
単体テストのTipsですが、
「1+1は2のはず」みたいな、絶対にパスするテストを一個入れておくと、思いのほか役に立つので、追加してください。
テストがfailしたとき、テスト環境が悪いのか、テストそのものが悪いのか切り分けたり、
テストの書き方忘れた時に思い出すメモとして、わざといろんな書き方しておいたり。

2022-12-17 04:40 UTC, shin-sforzando commented on README.md
> +To test using Vitest and check coverage, `npm run test:unit`.
PrerequisiteにVitest追記しますか。

2022-12-17 04:40 UTC, shin-sforzando commented on package.json
> +    "test:unit": "vitest --run && vitest run --coverage"
```suggestion
    "test:unit": "vitest run --coverage"
```

`vitest run --coverage` でテストも実行されてます。

2022-12-17 08:17 UTC, shin-sforzando requested changes

2022-12-17 08:17 UTC, shin-sforzando commented on src/__tests__/calculate.ts
> +}
ん？テストじゃないファイルが `__tests__` にあるの変です。

Calculate.test.tsって名前にしたら、本システムの計算に関するテストがあると期待されるので、Sample.test.tsとかが良いでしょう。そして、それは何もインポートせず、ただ「1+1が2と期待される」って書くだけです。

2022-12-17 09:16 UTC, shin-sforzando commented on src/__tests__/Sample.test.ts
> +  it('1 + 1 = 2', () => {
`describe` と `it` がなんなのか理解してますか？

2022-12-17 11:09 UTC, yktt-nuane commented on src/__tests__/Sample.test.ts
> +  it('1 + 1 = 2', () => {
`describe`はtestが増えてきた時に、整理したり再利用したりできるのかなって思っています。
`it`は例えばsnapshotとかを設定するときに使う名前を定義しているのかなって思っています。

2022-12-18 03:56 UTC, shin-sforzando commented on src/__tests__/Sample.test.ts
> +  it('1 + 1 = 2', () => {
> 定義しているのかなって思っています。

いや、オープンソースソフトウェアの世界で「思う」なんてしなくて良いです。
調べたら全部答えはあります。最終的にソースコードまで辿れるのがOSSの良いところなんですから。

VitestのAPI Docに答えはありますが、
https://vitest.dev/api/
そもそもdescribe/it構文はVitest特有ではなく、初出はJava用フレームワークJUnitかRuby用フレームワークRspecあたりの、かなり古い構文です。
https://sites.google.com/site/unclebobconsultingllc/specs-vs-tests

describeは横山さんの言う通り、テストの集まりを表すものですが、再利用のためではなく、シナリオを表すため、と考えた方が良いでしょう。
たとえばHome.test.tsは言うまでもなくHomeコンポーネントをテストするものですが、Homeコンポーネントをテストすると言ってもレンダリングが正しいことをテストするのかコンポーネント内部のロジックが正しいことをテストするのか、コンポーネントの子どもたちが正しいことをテストするのか、いろんな軸のテストが考えられるので、それらをまとめるためのものです。

itは、これもVitestのAPI Docにも例がありますが、

```ts
it('should return the correct square root', () => {
  expect(Math.sqrt(4)).toBe(2)
```

のように英文、そして基本的にshouldから始まる文章を書きます。
見ての通り、その内部にあるテストが「どうあるべきか」を書きます。
(ちなみにVitestの `it()` は `test()` のエイリアスです)

ここを書くときに横山さんがどんな思考をしたかエミュレートしたんですが、「Home.test.ts見ても存在しないけど、なんとなく文字列だな」程度で書き進めてますね。
見る人が見たらこの2行だけで、その人が理解してないまま実装してるのがバレてます。

2022-12-18 04:09 UTC, shin-sforzando commented on src/__tests__/Sample.test.ts
> +  it('1 + 1 = 2', () => {
「正しいコードを書いてない」ことより「説明できないコードを書いている」ことを真に恐れてください。

何かを参照したりコピペするのは大いに結構ですが、レビュアーに「これはなんですか？どうしてこう書いたんですか？」と質問されて、説明できないコードを3回書いたら弊社では解雇です。マジです。これで解雇になった人が3人実在します。
説明できないコードを書いてる人は伸びないので定期的に賃金を払って成長を待つのが無駄だからです。

2022-12-18 07:34 UTC, shin-sforzando reviewed
細かい点を修正するコミットを送りました。

2022-12-18 07:34 UTC, shin-sforzando commented on package.json
> +    "test:unit": "vitest run --coverage",
https://github.com/yktt-nuane/shiftmaking/pull/45#discussion_r1045166643 の会話を思い出して欲しいんですけど、
`:` は慣例的にオプションなので、親がいないのに子だけ定義されてる違和感を解消すべく書き換えました。

2022-12-18 07:34 UTC, shin-sforzando commented on package.json
> +    "vite-tsconfig-paths": "^4.0.3",
これも本番環境では使ってなかったので `devDependencies` に移動しました。

2022-12-18 07:34 UTC, shin-sforzando commented on src/__tests__/Sample.test.ts
> +describe('Vitest Sample', () => {
ここはSuiteを説明する部分なので"calculate"なんて意味をなさない文章を差し替えました。
ちなみに、クラスやメソッドの命名でも"calculate"や"manage"など、実質的な説明の意味をなさない単語は嫌われます。

2022-12-18 07:34 UTC, shin-sforzando commented on src/__tests__/Sample.test.ts
> +  it('should always be truthy', () => {
「正しいSumを計算する」になっていましたが、Sumとは「合計」であって、つまり、3個以上の値の総和を意味します。
単なるに変数の足し算はaddition、しかも足し算の正しさを確かめたいのではなく、「常にパスする」ことを確かめたいので、そのように書き換えました。

2022-12-18 07:34 UTC, shin-sforzando commented on README.md
> +`npm run test:unit` to run unit tests.
> `npm run dev` to start development server.

の記法に揃えました。
かつ、カバレッジレポートがどこに出力されるかを追記しました。

2022-12-18 09:20 UTC, yktt-nuane commented on README.md
> +`npm run test:unit` to run unit tests.
その他の部分も同様の記法に揃えるように修正しました。

2022-12-18 10:26 UTC, shin-sforzando requested changes

2022-12-18 10:26 UTC, shin-sforzando commented on README.md
> +- [shiftmaking](#shiftmaking)
TOCとして、 `shiftmaking` というタイトルが出てくるのは変（説明書のなかに「説明書」という章は普通ないでしょう？）なので `markdown.extension.toc.levels` を `2..6` にするなどして除外します。
除外するにはいろいろな方法がありますので、他の方法でも良いです。

cf. https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#table-of-contents

2022-12-18 11:21 UTC, yktt-nuane commented on README.md
> +- [shiftmaking](#shiftmaking)
<img width="302" alt="image" src="https://user-images.githubusercontent.com/61369434/208295476-7a8d34dc-b4bb-4c69-8009-f2ea59301471.png">
これが一番しっくりきたので、`<!-- omit in toc -->`で除外しました。

2022-12-18 12:06 UTC, shin-sforzando commented on README.md
> +- [shiftmaking](#shiftmaking)
まぁ、そう思いますよね…
間違ってないんですが、念のために伝えておくと、Markdownは処理系がたくさんあって、すなわち方言がたくさんあります。
see. https://ja.m.wikipedia.org/wiki/Markdown
なので、特殊な記法を使って、それが全員の環境に反映されるかは怪しいところです。
かつ、このコメントが何を意味するか気になった人がいたら、コメントのコメントはないので調べるのが少し大変でしょう。
ましてや1行目へのコメントとなると「何か大事なコメントなのでは？」と思うでしょうね。
(ご存知のとおり、プログラム界隈では1行目に重要なshebangやエディタ向け文字コード指定を書く文化があります)

2022-12-18 12:08 UTC, shin-sforzando approved these changes
おつかれさまです。
LGTMです。

2022-12-18 12:08 UTC, merged