prepare continuous integration
yktt-nuane/shiftmaking pull request #48
Opened 2022-12-19 03:29 UTC by yktt-nuane

## Describe the PR

To close #3 

## Screenshots

None

## Detail of the change

(T. B. D.)

- [ ] introduce continuous integration using GitHub Actions

## Anticipated impacts

- [ ] run GitHub Actions

## To reproduce

(T. B. D.)

## Appendix

None

2022-12-19 11:28 UTC, shin-sforzando requested changes
「CIで何をしたいか」がわからないのでコードが正しくともApproveできません。

2022-12-19 11:28 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +        node-version: [18]
単一バージョンなら `matrix` 使う意味がないのでは。

2022-12-19 11:28 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +    branches: [main]
```suggestion
    branches:
      - main
  pull_request:
  workflow_dispatch:
```

`main` がPRになるはずがないですね。
それから手動で実行できるように `workflow_dispatch:` を追加しました。

2022-12-19 12:35 UTC, shin-sforzando requested changes
GitHub Actions公式にBadgeを用意してくれてるのでREADME.mdに追加しましょうか。

```
[![CI](https://github.com/yktt-nuane/shiftmaking/actions/workflows/ci.yml/badge.svg)](https://github.com/yktt-nuane/shiftmaking/actions/workflows/ci.yml)
```

2022-12-19 12:35 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +      - name: Unit test using Vitest
Vitestって書く意味ないですね。

2022-12-19 12:42 UTC, shin-sforzando requested changes

2022-12-19 12:42 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +      - run: npm run build --if-present
`--if-present` をつけているのはなぜですか？

2022-12-19 12:42 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +        run: npm install
`npm` にはCIでのインストール用に `npm ci` が用意されているので、そちらを使いましょう。

cf. https://docs.npmjs.com/cli/v9/commands/npm-ci

2022-12-19 12:42 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +        run: npm run test:unit
VItestの結果をGitHub側に表示してくれるレポーターがあるので導入を検討しませんか。

cf. https://www.npmjs.com/package/vitest-github-actions-reporter/v/0.7.0

2022-12-19 23:05 UTC, yktt-nuane commented on .github/workflows/ci.yml
> +      - run: npm run build --if-present
`npm run test`などが準備されていない時に`npm run build`してもエラーが出ないようにするためのものですが、今回は準備されてから`npm run build`している状況なので、不要ですね。

2022-12-20 00:54 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +      - run: npm run build --if-present
と言うか、正しく動作するかを確認するためのCIなら、正しく動作してないのを許容したら元も子もないですよね。

2022-12-20 01:29 UTC, shin-sforzando requested changes

2022-12-20 01:29 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +          node-version: '18.x'
`18.x` という指定は公式に認められてないですね。

```suggestion
          node-version: '18'
```

あと、 `setup-node` は簡単にキャッシュが使えるので追加しておくと良いです。
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md

2022-12-20 03:56 UTC, shin-sforzando approved these changes
LGTM.

2022-12-20 04:16 UTC, merged