start
yktt-nuane/shiftmaking pull request #52
Opened 2022-12-22 10:40 UTC by yktt-nuane

## Describe the PR

To close #7 

## Screenshots

None

## Detail of the change

- [ ] Introduce New Relic

## Anticipated impacts

None

## To reproduce

(T. B. D.)

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Appendix

None

2022-12-24 09:53 UTC, shin-sforzando commented
"To reproduce"、明らかに足りないです。

2022-12-24 12:44 UTC, yktt-nuane commented
申し訳ありません。修正しました。

2022-12-24 12:54 UTC, shin-sforzando commented
ん、まだまだ全然足りないです。
僕が知る限りでも少なくとも.env.localの復号と追加したパッケージのインストールが必要なはずです。
また、「コンソール」が何を指すかわかりません。手元のCLIですか？
New Relic上であれば当該のURLは必須で、
うまく行っている状態のスクリーンショットを添えると尚良いでしょう。
さらに、buildをした時点でログが吐かれる、とありますね。ということはGitHub Actions上でbuildされたもの、Vercel上でbuildされたものからも吐かれているはずですね？

2022-12-24 12:57 UTC, shin-sforzando commented
あと、コードのレビューを始めてから指摘しようと思ってましたが後出しじゃんけん的に思われるのも本意ではないので先に言うと、 `ts-ignore` がついたコードはよほどの事情がない限りApproveされることはないです。
それなら最初からTypeScript使わない方が良いです。

2022-12-24 12:58 UTC, shin-sforzando commented
もひとつ、merge先とコンフリクトしてる旨、警告出てますので、それも要修正です。

2022-12-25 10:41 UTC, shin-sforzando commented
繰り返しますが、再現手順に `.env.local` の復号は不要なんですね？

2022-12-25 10:42 UTC, shin-sforzando commented
> 4. debug - Home

ってどういう意味ですか？

2022-12-25 10:43 UTC, shin-sforzando requested changes
再現できなかったのでRejectします。

2022-12-25 13:49 UTC, shin-sforzando commented
以前にお伝えしたとおり、暗号化された環境変数のkeyについてはREADME.mdに記載しておいた方が良いです。
それがないとレビュアーは正しく復号できたかどうかもわかりません。
また、そのkey-valueをCIにも設定したかはauthorしかわからないのならば、それはDetail of the Changesに書いた方が良いでしょう。

2022-12-25 13:56 UTC, shin-sforzando commented
> CLIにdebug - Homeと表示される

実行した環境のCLIという意味ですか？
それであれば、以前から出来てたことと何が違うのかわかりませんよ？
このIssue&PRではどの環境からのログも1箇所に集約される状態を目指しているのですから、それを試す(各環境で変わる環境変数を埋め込んだログを吐くなど)、それがAxiom上で表示されているスクリーショットを貼るのが良いのでは？

2022-12-26 12:14 UTC, yktt-nuane commented
> > CLIにdebug - Homeと表示される
> 
> 実行した環境のCLIという意味ですか？ それであれば、以前から出来てたことと何が違うのかわかりませんよ？ このIssue&PRではどの環境からのログも1箇所に集約される状態を目指しているのですから、それを試す(各環境で変わる環境変数を埋め込んだログを吐くなど)、それがAxiom上で表示されているスクリーショットを貼るのが良いのでは？

環境で変わる環境変数を埋め込んでログを吐くのを実装する方法が分からないです。

2022-12-26 12:29 UTC, shin-sforzando commented
https://nextjs.org/docs/basic-features/environment-variables
https://vercel.com/docs/concepts/projects/environment-variables
https://docs.github.com/en/actions/learn-github-actions/environment-variables

2022-12-27 01:38 UTC, yktt-nuane commented
ちょっと混乱しているので、把握するのに、時間かかりそうです。

2022-12-27 02:13 UTC, shin-sforzando commented
横山さんの質問は「どこまでやって」「何が起きていて」「どうしたいか」が抜けています。
つまり"何"を聞いている質問なのかがわからなく、取り急ぎ、最初のキーワード「環境変数」に関連する公式ドキュメントのリンクを送りました。
cf.
- https://manabiya-sakura.com/information_technology/id=2263/
- https://qiita.com/seki_uk/items/4001423b3cd3db0dada7

2022-12-27 10:59 UTC, yktt-nuane commented
VercelとAxiomを連携させて、Axiomでアプリのログを確認できるところまで実装できました。それを確認してもらうための方法として、「各環境で変わる環境変数を埋め込んだログを吐くなど」と提案をもらいましたが、それを実現する方法が分からないです。添付の資料を読んでGithub ActionsのCIに埋め込む方法がいいのかなと思いました。

2022-12-28 04:36 UTC, shin-sforzando commented
- 環境変数をNext.js内で使う方法は理解していますか？
- Next.jsからAxiomへログを出力する方法を理解していますか？
- 各環境に固有の環境変数にどのようなものがあるかを理解していますか？
- 各環境に任意の環境変数を設定する方法を理解していますか？

2022-12-28 05:20 UTC, yktt-nuane commented
> * 環境変数をNext.js内で使う方法は理解していますか？
理解しています。
> * Next.jsからAxiomへログを出力する方法を理解していますか？
理解しています。
> * 各環境に固有の環境変数にどのようなものがあるかを理解していますか？
理解していません。まず質問の各環境に固有の環境変数が理解できません。
> * 各環境に任意の環境変数を設定する方法を理解していますか？
理解していません。

2022-12-28 07:01 UTC, shin-sforzando commented
あれ。各プラットフォーム固有の環境変数はそれこそ https://vercel.com/docs/concepts/projects/environment-variables 読んだら書いてますよ？

2022-12-28 10:12 UTC, yktt-nuane commented
Production, Preview, Developmentのそれぞれに環境変数を設定して、それをpushした時に読み込ませる形にするのでしょうか？

2022-12-28 10:59 UTC, shin-sforzando commented
> このIssue&PRではどの環境からのログも1箇所に集約される状態を目指している

つまり、あるログがどんな環境から生じたのかを知りたいですよね。それがVercelのProd環境なのか、誰かのローカル環境なのか。

2022-12-28 11:04 UTC, yktt-nuane commented
そうです。

2022-12-28 15:37 UTC, shin-sforzando commented
ん？そしたら既に材料は出揃ってるので組み合わせる実装するだけでは？

2022-12-28 15:37 UTC, shin-sforzando commented
何がわからないのかわからないです。

2022-12-30 00:03 UTC, yktt-nuane commented
質問も分からない状態なので、申し訳ないです。どこが分からないのかも分からなくなってきました。

2022-12-30 00:32 UTC, yktt-nuane commented
多分、意図したメッセージをlogに吐き出す方法がわかっていないです。

2022-12-30 04:26 UTC, shin-sforzando commented
ん、それならnext-axiomのREADME.mdに書いてると思うんですが
https://github.com/axiomhq/next-axiom
これで出来ないようなことをしたい、ということでしょうか？

2022-12-30 06:52 UTC, yktt-nuane commented
<img width="853" alt="image" src="https://user-images.githubusercontent.com/61369434/210042812-60a242e0-7777-4456-bf07-fd0234f1a10f.png">
ここが理解できないです。

2022-12-30 07:19 UTC, shin-sforzando commented
理解できない、というのは試してもそのとおり動かなかった、ということですか？

2022-12-30 08:36 UTC, yktt-nuane commented
いえ、試し方が分からないです。

2022-12-30 09:12 UTC, shin-sforzando commented
？ `src/pages/index.tsx` で既に試そうとしてますよね？

2022-12-30 09:16 UTC, yktt-nuane commented
<img width="853" alt="image" src="https://user-images.githubusercontent.com/61369434/210054040-fe9d7871-c738-40e1-b460-4fefd3492ef4.png">
ここまではできましたが、その先が分からないです。

2022-12-30 09:39 UTC, shin-sforzando commented
？ え、そこまで出来て何が難しいのかわからない。
たとえば https://vercel.com/docs/concepts/projects/environment-variables にある `VERCEL` を見たら「Vercelで動いてるか否か」がわかりますよね？

2022-12-30 11:01 UTC, yktt-nuane commented
Vercelで環境別にEnvironment Variablesを環境別に設定して、動いていることは確認できます。

2022-12-30 11:10 UTC, shin-sforzando commented
ん？[日本語でおk](https://gimon-sukkiri.jp/nihongodeok/)ですよ？

2022-12-30 12:27 UTC, yktt-nuane commented
<img width="918" alt="image" src="https://user-images.githubusercontent.com/61369434/210069876-af1cc6f3-7a1a-46be-aed7-d50877023272.png">
上のスクショのように、Production、Preview、Developmentに対して環境変数を設定して、下のスクショのようにVercel CLIを使って環境変数が読み込む事を確認することはできます。
<img width="823" alt="image" src="https://user-images.githubusercontent.com/61369434/210070153-f499c4d4-5559-45a2-8fa2-ed70e7afc6df.png">

2022-12-30 21:21 UTC, shin-sforzando commented
そうですね、Axiom課金してないのでスクリーンショットでも貼ってくれないと何もわからないんで、そうやって見せてもらえるのはありがたいですが、
しかし、やりたいこととやらなきゃいけないことが乖離してますね。

今、「ログがどこから来てるのか」を知りたいんだから、
Vercelにもともとセットされてる(=固有の)環境変数使うだけで十分で、

```ts
const PLATFORM_ENV = process.env.NEXT_PUBLIC_VERCEL_ENV
switch (PLATFORM_ENV) {
  case 'production':
    log.info('This log is output from Vercel(Production).')
    break
  case 'preview':
    log.info('This log is output from Vercel(Preview).')
    break
  case 'development':
    log.info('This log is output from Vercel(Development).')
    break
  default:
    log.info('This log is output from Unknown.') // Perhaps it is someone's local.
}
```

仮に今後Vercel以外からホストされること考えたとしても、たったこれだけのこと。

2022-12-31 00:27 UTC, yktt-nuane commented
> しかし、やりたいこととやらなきゃいけないことが乖離してますね。

その通りでした。

これが実装できている事を、Axiomで確認するにはどうしたらいいでしょうか？
log.info()の中身を手元のCLIで確認する事はできますが、Axiomで確認する方法が分かりません。

2022-12-31 06:23 UTC, shin-sforzando commented
容易にこうなるので口酸っぱく「ゴールを明確に」と。そして、この状態になると主語不明瞭や細かい単語ミスも事態の混乱をより加速するので、日ごろから気にしてなきゃいけないのです。

確認方法は、単純に各環境にデプロイ&アクセスして当該のログが出てくるかをAxiom上で目視するのが良いかと。

2022-12-31 06:24 UTC, shin-sforzando commented
ちなみに私のサンプルコードはわかりやすさ最優先で書いてますが、もっと短く綺麗に書けますし、書く場所もHomeじゃないですね。

2022-12-31 13:10 UTC, shin-sforzando commented
2枚のスクリーンショットがどの状態で撮影されたか教えてください。

2022-12-31 13:13 UTC, shin-sforzando commented
今後、SSGまたはSSR(ISRを含む)する予定はありますか？

2023-01-01 12:51 UTC, yktt-nuane commented
[https://www.shiftmaking.com](https://www.shiftmaking.com)にアクセスすると、下の図のログがでます。
<img width="652" alt="image" src="https://user-images.githubusercontent.com/61369434/210170955-2654895c-6010-471a-aa75-da1ce5689a7f.png">

[https://shiftmaking-45fshesa6-yktt-nuane.vercel.app/](https://shiftmaking-45fshesa6-yktt-nuane.vercel.app/)にアクセスすると'This log is output from Vercel(Preview).'というmessageがAxiomに出力されるはずですが、Previewのログ自体が反映されません。何か間違っていますでしょうか？

適当に作ったrepositoryで同じ手順を踏むと、反映されます。

VS Codeのソース管理のところに下図のように、いつもと違う「変更の同期」が表示されており、このbranchに問題があると考えています。

<img width="692" alt="image" src="https://user-images.githubusercontent.com/61369434/210171073-89b15248-0cb6-4ad0-a70f-e6968e192102.png">

2023-01-01 12:53 UTC, yktt-nuane commented
> 今後、SSGまたはSSR(ISRを含む)する予定はありますか？

予定ありです。

2023-01-01 13:21 UTC, shin-sforzando commented
> VS Codeのソース管理のところに下図のように〜

それは手元の更新がPushされてないのでは？

> Previewのログ自体が反映されません

手元の更新が反映されてないせいかもしれませんし、何かが足りないのかもしれませんね。
(その何かは私の方ではわかりません。GitHubのAdmin権も持ってませんし、Axiomへのアクセス権もないので)

2023-01-01 13:23 UTC, shin-sforzando commented
> 予定ありです。

問題です。今、最初にアクセスしているHomeはSSG/SSR(ISR)/CSR、どれでしょうか？

そして、三つのうち残り二つからもログが出力されるかを確かめるにはどうしたら良いでしょうか？

2023-01-01 13:44 UTC, yktt-nuane commented
<img width="326" alt="image" src="https://user-images.githubusercontent.com/61369434/210172698-4a5634fb-0024-4fef-b1fb-7b93acf94765.png">
pushが完了してからも残っていて、カーソルを合わせるとこんなメッセージが出ます。
今まで、こんな事にはなっていなかったです。Merge Conflictのアラームが出ていたのを解消した時から、何かいつもと違って困っています。

2023-01-01 13:50 UTC, yktt-nuane commented
> 問題です。今、最初にアクセスしているHomeはSSG/SSR(ISR)/CSR、どれでしょうか？
> 
> そして、三つのうち残り二つからもログが出力されるかを確かめるにはどうしたら良いでしょうか？

今のHomeは、CSRだと思います。SSGとSSRを確認するには、getServerSidePropsとgetStaticPropsで、Vercelの環境変数を読み込んだpageを作成して、アクセスして、ログを確認するのでどうでしょうか？

2023-01-02 05:22 UTC, shin-sforzando commented
> pushが完了してからも残っていて <snip> Merge Conflictのアラームが出ていたのを解消した時から、何かいつもと違って困っています。

Merge Conflictをどう解消したのかがわからないのでアドバイスできませんが、
Conflictが解消された後、リモートと同期が取れていますか？
単純に手元にあるファイルたちとこのPRのファイルに一切の差分はありませんか？

2023-01-02 05:58 UTC, shin-sforzando commented
> 今のHomeは、CSRだと思います。

<img width="1647" alt="Screenshot 2023-01-02 at 14 29 33" src="https://user-images.githubusercontent.com/32637762/210197667-ce526aaf-fdbd-4907-86c1-0438271dfd5d.png">

答えは「思う」とか推測する必要はなく、 `npm run build` してみればわかります。
`/` は `○  (Static)  automatically rendered as static HTML (uses no initial props)` 、つまり静的なHTMLが生成されました。
強いて言うならSSGです。イメージで言えば `getStaticProps()` で無(= 当然、冪等)をfetchしたと認識されてのSSGです。
（厳密には（Data Fetching的な意味では）SSGでもないのですが、例えば当該のPageにアセットがあったらビルド時に最適化されたりするので、SSG / SSR / CSRの3択から選べ、と言われたら一番近いのはSSG、って感じです）
詳細はこちら → https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering

> SSGとSSRを確認するには、getServerSidePropsとgetStaticPropsで〜

と言うことで、確認しなければならないのはSSRとCSRなんですが、
Next.js 13からはSSR向けにServer Componentと `fetch()` が用意されました。
CSR向けにはClient Componentと `use` が用意されています。
https://beta.nextjs.org/docs/data-fetching/fundamentals

Next12までの概念の方がわかりやすいと思うので、そちらで説明すると
SSRを確認するには例えばAPI Routeを使って乱数を返すエンドポイントを作成し、 `getServerSideProps()` で乱数を取得表示できれば良さそうですね。
同様に、CSRを確認するには `useEffect` 内でこちらのエンドポイントを叩いて乱数を取得表示できればOK、となります。

2023-01-02 08:39 UTC, yktt-nuane commented
> Merge Conflictをどう解消したのかがわからないのでアドバイスできませんが、
> Conflictが解消された後、リモートと同期が取れていますか？
> 単純に手元にあるファイルたちとこのPRのファイルに一切の差分はありませんか？

同期は問題なく、差分はないです。
<img width="600" alt="image" src="https://user-images.githubusercontent.com/61369434/210209194-51f0a3c3-b863-47d4-ae6a-29f3e9cf43b1.png">

2023-01-02 08:42 UTC, yktt-nuane commented
> 答えは「思う」とか推測する必要はなく、 npm run build してみればわかります。〜

理解しました。公式Docを復習します。

> SSRを確認するには例えばAPI Routeを使って乱数を返すエンドポイントを作成し、 getServerSideProps() で乱数を取得表示できれば良さそうですね。
> 同様に、CSRを確認するには useEffect 内でこちらのエンドポイントを叩いて乱数を取得表示できればOK、となります。

SSRとCSRのログがAxiomで確認できるかを検証する必要があるという事ですね。

2023-01-02 10:24 UTC, shin-sforzando commented
> 同期は問題なく、差分はないです。

`git log --graph` で見るとどうなってます？
cf. https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-use-the-git-log-graph-command

2023-01-02 10:25 UTC, shin-sforzando commented
> SSRとCSRのログがAxiomで確認できるかを検証する必要があるという事ですね。

将来的に使う予定があるなら、コードがややこしくなる前に簡単にチェックしてしまうのをオススメします。

2023-01-02 10:27 UTC, yktt-nuane commented
> git log --graph で見るとどうなってます？

<img width="869" alt="image" src="https://user-images.githubusercontent.com/61369434/210219324-f7cb0f73-e6b4-4710-8df3-5e638618d3b5.png">

2023-01-02 10:32 UTC, shin-sforzando commented
skipping前と同じコミットが繰り返されてるの、なんででしょね。

2023-01-02 10:35 UTC, yktt-nuane commented
> skipping前と同じコミットが繰り返されてるの、なんででしょね。

分からないです。

2023-01-02 13:13 UTC, yktt-nuane commented
SSRをテストするためのAPI（api/logtest.tsx）を作成して、index.tsxのSSRで読み込むコードを書いてみました。`fetch`を使う場合の`internal path`の設定で躓いています。local環境のCLIでは確認することができました。
<img width="532" alt="image" src="https://user-images.githubusercontent.com/61369434/210236114-0d9e7611-4323-4590-ba7e-a71410664380.png">

まずは、今の方向性でいいかを教えて欲しいです。

2023-01-02 13:32 UTC, shin-sforzando commented
結論、その方向性の前にやらなきゃいけないことが残ってます。

まず、Gitの使い方から正しましょうか。
cf. https://blog.masuyoshi.com/gitコミットの粒度はレビュワーを常に意識/

同じコミットメッセージのコミットが連続してたらタイムマシンの意味無くなりますよね。
先のコミットログがおかしい現象でそれを痛感しませんか？
また、通常、レビュアーはコミット単位でソースコードの変更を追っています。コミットメッセージとコードの変更が不一致なのはレビュアー泣かせです。

apiの前にPreview時にログが出ない理由を解明しましょうよ。
私は「コードがややこしくなる前に」ってわざわざ言ってるんですよ。

2023-01-02 23:38 UTC, yktt-nuane commented
> apiの前にPreview時にログが出ない理由を解明しましょうよ。

承知です。

2023-01-03 06:49 UTC, yktt-nuane commented
Preview時にログが出ない理由になっている可能性があるので、まずは、GitHubのbranchがいつもと違う状況なのを解消したいです。

> skipping前と同じコミットが繰り返されてるの、なんででしょね。

これに関して、何か調べるべき事はありますか？

2023-01-03 08:17 UTC, shin-sforzando commented
これが単なる表示の問題なのか、本当にそういうログなのか調べましょう。
`git log` にはいろんなオプションがあります。
cf. https://git-scm.com/docs/git-log

2023-01-03 08:18 UTC, shin-sforzando commented
まず公式ドキュメントを原典としてあたるようにしてください。
それでわからなかった時に「公式ドキュメントの〜を読んで試しましたが」と添えて質問するようにしましょう。

2023-01-03 11:56 UTC, yktt-nuane commented
`https://git-scm.com/docs/git-log`を参考にして、`git log --oneline --graph`コマンドで、履歴を確認しました。

main branchでの結果は下図
<img width="880" alt="image" src="https://user-images.githubusercontent.com/61369434/210348315-64622177-acde-4b0f-9529-435656cbc6d0.png">

007_prepare_logging_toolでの結果は下図
<img width="897" alt="image" src="https://user-images.githubusercontent.com/61369434/210348474-307bd026-3cd5-45ea-9d1a-d91f572a7534.png">

でした。これを見る限り、正常です。現在のPreviewはエラーが出る状態なので、Axiomでerror messageのログが出るか試してみるため、[Preview](https://shiftmaking-ha97dqw0n-yktt-nuane.vercel.app/)にアクセスすると、Axiomがログを吐いていました。（下図）
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/61369434/210349070-5e6de613-2aea-41d8-bb21-4392529b2e21.png">

branchは正常で、ソースコードの問題（`'This log is output from Vercel(Preview).'`を出力するためのソースコードの問題）であることがわかりました。

なので、目的のメッセージをPreviewのログで確認できる状態にソースコードを修正する必要があります。

> ちなみに私のサンプルコードはわかりやすさ最優先で書いてますが、もっと短く綺麗に書けますし、書く場所もHomeじゃないですね。

サンプルコードを利用して、PreviewのURLにアクセスした際に、`'This log is output from Vercel(Preview).'`が出力される事を確認する段階（[c6aae3c](https://github.com/yktt-nuane/shiftmaking/pull/52/commits/c6aae3caa7eb09de6610cbc1d07de6b761247753)）に戻っても良いでしょうか？

2023-01-03 13:33 UTC, shin-sforzando commented
この問いに答えずに作業優先していただいても良いんですが、Previewでログが出ない原因をどのように予想してます？
デバッグを仮説検証のように進められる人は、得るものが大きいのでおすすめです。
(初期仮説を構築するための材料すらない、と言う状況もあり得るので全てに言えるわけではないですが）
「AかBかCのいずれかが怪しい、うち、Aか否かを判定する実験は容易い、…結果Aではなかったので続いてBかCを追う」、人狼ゲームみたいな感じです。

2023-01-05 08:12 UTC, shin-sforzando commented
> https://www.shiftmaking.com/にアクセスして得られるログ

の部分、変に切り抜かずにブラウザで見えてるままのスクリーンショットに差し替えてもらえますか？

2023-01-05 08:28 UTC, shin-sforzando requested changes
![2023-01-05 17 27 26 0 0 0 0 d95edf615e9d](https://user-images.githubusercontent.com/32637762/210735120-34f0d4a4-1f62-409f-bcf1-e59890d23f8d.png)

2023-01-05 08:37 UTC, shin-sforzando requested changes

2023-01-05 08:37 UTC, shin-sforzando commented on .eslintrc.json
> +    "@typescript-eslint/no-var-requires": "off",
https://github.com/yktt-nuane/shiftmaking/pull/52/files#diff-882b2c04b01b2e8b2cdcf1817c30ea503a8005f1c0d54cfff37053b6801fea85R1 のためだと思いますが、
この1行のために全ファイルへのルールを変更するのはやり過ぎだと思います。
当該行だけignoreするようにしましょう。

2023-01-05 08:37 UTC, shin-sforzando commented on src/pages/_app.tsx
> +  }
```suggestion
  if (process.env.NEXT_PUBLIC_VERCEL_ENV) {
    log.info(`This log is output from Vercel: ${process.env.NEXT_PUBLIC_VERCEL_ENV}.`)
  } else {
    log.info('This log is output from Unknown.')
  }
```

説明的にせず、より簡潔に書くなら、私ならこんな感じですね。

2023-01-05 08:37 UTC, shin-sforzando commented on src/pages/index.tsx
> +  LOG_TEST: any
explicitなanyは禁止されてるはずでは？

2023-01-05 08:37 UTC, shin-sforzando commented on README.md
> +SECRET=***
Axiomのトークンがセットされてない環境（例えばローカル環境）でもAxiomにログ飛ぶんでしたっけ？
https://www.axiom.co/docs/reference/settings#api-token

2023-01-05 08:37 UTC, shin-sforzando commented on src/pages/index.tsx
> +}
https://github.com/yktt-nuane/shiftmaking/pull/52#issuecomment-1368674216

> Next.js 13からはSSR向けにServer Componentと fetch() が用意されました。
> CSR向けにはClient Componentと use が用意されています。
> https://beta.nextjs.org/docs/data-fetching/fundamentals

って書いたの覚えてます？
つまり、Next13方式にはしない、ってことで良いですか？

2023-01-05 11:26 UTC, yktt-nuane commented on README.md
> +SECRET=***
飛ばないみたいです。`vercel dev`でも`npm run dev`でも飛ばないです。
.env.localを修正して秘匿化します。

2023-01-05 11:36 UTC, yktt-nuane commented on src/pages/index.tsx
> +}
Next13方式にします。

2023-01-06 04:10 UTC, shin-sforzando requested changes

2023-01-06 04:10 UTC, shin-sforzando commented on src/pages/index.tsx
> +}
個人的には「Obsoleteだから採用しない」はあっても「Betaだから採用しない」はないですね。
開発陣のやり取りを見てもBetaなのは `/app` ディレクトリについてであって、ServerComponentsはReactでも採用されましたし、たとえばMantineなども粛々とNext13対応してるので、今から12向けのコードにこだわる理由はないかなと思います。
cf. https://github.com/mantinedev/mantine-next-template/tree/next-13-app

2023-01-06 04:10 UTC, shin-sforzando commented on next.config.js
> +const { withAxiom } = require('next-axiom')
[`@typescript-eslint/no-var-requires`](https://typescript-eslint.io/rules/no-var-requires) に引っかかるの、ここですよね。
`LOG_TEST: any` じゃないですよ。

2023-01-06 04:10 UTC, shin-sforzando commented on README.md
> +SECRET=***
今の `.env.local` こうなってないですね。
AxiomのAPI TOKENも設定されてないようです。

2023-01-06 23:49 UTC, yktt-nuane commented on src/pages/index.tsx
> +}
そうなんですね。了解いたしました。Next13方式にします。

2023-01-08 05:44 UTC, yktt-nuane commented
> 個人的には「Obsoleteだから採用しない」はあっても「Betaだから採用しない」はないですね。
> 開発陣のやり取りを見てもBetaなのは /app ディレクトリについてであって、ServerComponentsはReactでも採用されましたし、たとえばMantineなども粛々とNext13対応してるので、今から12向けのコードにこだわる理由はないかなと思います。

難渋しています。
https://beta.nextjs.org/docs/data-fetching/fetching
これのappフォルダからルーティングは分かりましたが、Data Fetchingを実際にどうやって書くかが分からないです。

2023-01-08 06:26 UTC, yktt-nuane commented
<img width="782" alt="image" src="https://user-images.githubusercontent.com/61369434/211183494-799d1ec3-f3a5-4352-84ce-83a4396fbea8.png">
`@ts-ignore`が使えないので、一旦`"@typescript-eslint/no-var-requires": "off"`で進めます。

2023-01-08 13:46 UTC, shin-sforzando commented
> `@ts-ignore` が使えないので、一旦 `"@typescript-eslint/no-var-requires": "off"` で進めます。

そりゃ使えないですよ。型の問題じゃないですからね。
`// eslint-disable-next-line @typescript-eslint/no-var-requires` を使えば1行だけ無効にできますよ。
see. https://eslint.org/docs/latest/user-guide/configuring/rules#comment-descriptions

2023-01-08 13:55 UTC, shin-sforzando commented
> 難渋しています。
> https://beta.nextjs.org/docs/data-fetching/fetching
> これのappフォルダからルーティングは分かりましたが、Data Fetchingを実際にどうやって書くかが分からないです。

まず `src/pages/_app.tsx` があるの、ややこしくしてますね。
cf. https://beta.nextjs.org/docs/upgrade-guide#migrating-_documentjs-and-_appjs
あとはfetchするだけなら普通に公式ドキュメント通り書くだけだけどな…
ユニットテストでfetchがつまづくっていうなら、確かにちょっと罠が待ってるんですけど、その手前の話ですよね？

2023-01-09 03:39 UTC, yktt-nuane commented
> まず src/pages/_app.tsx があるの、ややこしくしてますね。
> cf. https://beta.nextjs.org/docs/upgrade-guide#migrating-_documentjs-and-_appjs
> あとはfetchするだけなら普通に公式ドキュメント通り書くだけだけどな…
> ユニットテストでfetchがつまづくっていうなら、確かにちょっと罠が待ってるんですけど、その手前の話ですよね？

その手前の話ですが、大丈夫そうです。ProductionとPreviewからのそれぞれのログをAxiomで確認する事ができました。Next13仕様だと基本がSSRになっているので、あとは、CSRで別のログを発生させるのを確認する流れでしょうか？

2023-01-09 10:25 UTC, shin-sforzando reviewed
> CSRで別のログを発生させるのを確認する流れでしょうか？

そうですね。それもそんなに難しくないと思います。

2023-01-09 10:25 UTC, shin-sforzando commented on src/app/head.tsx
> +      <title></title>
defaultのタイトルをセットしておきましょう。

2023-01-09 10:25 UTC, shin-sforzando commented on src/__tests__/Home.test.tsx
> +    main.getByRole('heading', { level: 1, name: /Shiftmaking/i })
この `/i` は意味を理解してますか？

2023-01-09 10:25 UTC, shin-sforzando commented on src/app/layout.tsx
> +      <head />
あれ、 `head.tsx` 使うときは `<head />` 要らないと思ったけどな。

2023-01-09 11:16 UTC, yktt-nuane commented on src/__tests__/Home.test.tsx
> +    main.getByRole('heading', { level: 1, name: /Shiftmaking/i })
大文字と小文字を区別しないという事ですが、Sを大文字にしているので、小文字にするかiを消すかの方が良いですかね。

2023-01-09 11:39 UTC, shin-sforzando commented on src/__tests__/Home.test.tsx
> +    main.getByRole('heading', { level: 1, name: /Shiftmaking/i })
そうです。厳密にやるなら `/i` を消す、やらないなら `S` を小文字にする、どっちでもなかったので違和感でした。

2023-01-11 04:48 UTC, yktt-nuane commented
現時点で、環境別の場合分けログが、Axiomで確認できない状態です。元々、`src/pages/_app.tsx`に格納してあった時は問題なく稼働していました。それを[0cc2724](https://github.com/yktt-nuane/shiftmaking/pull/52/commits/0cc2724ef7c3ba48ad119f10dc1d0c765183d0a6)のように、移行したらProductionとPreviewのログをそれぞれAxiomに反映できると思ったのですが、うまくいきません。逆に、`vercel dev`でアクセスしたログは、変更前は反映されませんでしたが、変更後は反映されています。

2023-01-11 05:23 UTC, shin-sforzando commented
そもそも `vercel dev` はREADME.mdにもPRのTo reproduceにも書いてないので、それで検証してるのがおかしいですね。
また、 `src/pages/_app.tsx` の中身は `src/app/layout.tsx` に移設するよう公式Docに書いてましたよね。
cf. https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app
`src/app/page.tsx` はNext12で言うところの `src/pages/index.tsx` 、つまり、 `/` にアクセスした際の挙動を記するところです。

そして、事象を忠実に理解してください。「**プログラムは思ったとおりに動かない、書いたとおりに動く**」
ProductionとPreviewで出力されず、Developmentでは出力されるならば、そう書いているのです。
つまり、 `if (LOG_TEST)` はProductionとPreviewでFalsyなんでしょう。
`LOG_TEST` がFalsyになる原因に心当たりはありませんか？
ヒントはこの辺だと思います。
https://github.com/yktt-nuane/shiftmaking/pull/52#issuecomment-1364685530

2023-01-11 05:42 UTC, yktt-nuane commented
> ProductionとPreviewで出力されず、Developmentでは出力されるならば、そう書いているのです。
> つまり、 if (LOG_TEST) はProductionとPreviewでFalsyなんでしょう。
> LOG_TEST がFalsyになる原因に心当たりはありませんか？

Falsyであれば、else条件の`'This log is output from Unknown.'`が出力されるはずですが、それも出力されてなくて困っています。
![image](https://user-images.githubusercontent.com/61369434/211726524-199c4978-87cb-42dc-82a3-173ddf954549.png)
上図で、`This is generated from vercel(Preview)`と出力されているので、環境変数の読み込みはできていると思います。

2023-01-11 08:11 UTC, shin-sforzando commented
> Falsyであれば、else条件の'This log is output from Unknown.'が出力されるはずですが、それも出力されてなくて困っています。

であれば、そのように書かれている、と言うことですね。
いかんせん、助けてあげたくても僕はAxiomもVercelも見れないので、何もできず。

2023-01-24 07:01 UTC, yktt-nuane commented
![image](https://user-images.githubusercontent.com/61369434/214230195-94fcce89-354d-4286-b663-9eed6e16981b.png)
`pages/_app.tsx`に記載していた、`export { reportWebVitals } from 'next-axiom';`をどこに移動するかが分かりません。

`pages/_app.tsx`は`app/layout.tsx`に移動するように指示されています。`app/layout.tsx`の先頭に`export { reportWebVitals } from 'next-axiom';`を追記すると、
`Layout "src/app/layout.tsx" exports an invalid "reportWebVitals" field. Layout should only export a default React component and configuration options. Learn more: https://nextjs.org/docs/messages/invalid-segment-export`
と言うエラーになります。
どこに移動すればいいのかを知りたいです。

2023-01-24 07:47 UTC, shin-sforzando commented
- エラーメッセージ中の https://nextjs.org/docs/messages/invalid-segment-export は読みましたか？
- WebVitalsとは何か理解していますか？

2023-01-24 11:30 UTC, yktt-nuane commented
> エラーメッセージ中の https://nextjs.org/docs/messages/invalid-segment-export は読みましたか？

> You can create a new file and co-locate it with the page or layout. In the new file, you can export any custom fields and import it from anywhere.

読みました。ファイルを新しく作って読み込む形になるようですが、具体的にどうするかが、分かりません。

> WebVitalsとは何か理解していますか？

多分、これが理解できていないので、具体的にどうするかが分かっていないのだと思います。
参考資料などありますか？
[https://web.dev/i18n/ja/vitals/](https://web.dev/i18n/ja/vitals/)とかであっていますか？

2023-01-24 12:18 UTC, shin-sforzando commented
> ファイルを新しく作って読み込む形になるようですが、具体的にどうするかが、分かりません。

に対して、実際に何を試しましたか？

> https://web.dev/i18n/ja/vitals/とかであっていますか？

あってます。つまり、Client-sideでの計測ですよね。
そして、Next13の `apps` 以下はどうなりましたか？
cf. https://zenn.dev/hamo/articles/31133919b987b9

2023-01-25 02:41 UTC, yktt-nuane commented
WebVitalsを`export { reportWebVitals } from 'next-axiom'`でモニタリングしようとしていて、`export { reportWebVitals } from 'next-axiom'`を含めた新しいClient Componentsのファイルを作成しておいて、それを読み込む形で使用する。
あっていますか？

2023-01-25 03:00 UTC, shin-sforzando commented
> WebVitalsを`export { reportWebVitals } from 'next-axiom'`でモニタリングしようとしていて、`export { reportWebVitals } from 'next-axiom'`を含めた新しいClient Componentsのファイルを作成しておいて、それを読み込む形で使用する。 あっていますか？

質問するよりやってみたら良いのでは？
やらない限りいつまでも調査力は上がりませんよ。

2023-02-24 08:20 UTC, yktt-nuane commented
Axiom不採用のため、このpull requestをcloseします。

2023-02-24 08:20 UTC, closed without merging