007 prepare logging tool part2
yktt-nuane/shiftmaking pull request #53
Opened 2023-02-16 22:30 UTC by yktt-nuane

## Describe the PR

To close #999

The relevant Issue must be specified.
Then explain **why** you implemented it this way for that.

## Screenshots

(T. B. D.)

If applicable, add screenshots to help explain your problem.

## Detail of the change

(T. B. D.)

A clear and concise description of what you changed.

- [x] A
- [ ] B
- [ ] C

## Anticipated impacts

(T. B. D.)

A clear and concise description of where may be affected by the changes.

## To reproduce

(T. B. D.)

Steps to check the behavior:

1. Update Libraries `...`
1. Import Database `...`
1. Reload Pages `...`
1. Click on `...`

## Appendix

(T. B. D.)

Add any other context about the problem here.

2023-02-26 09:02 UTC, shin-sforzando requested changes
おそらくですが、 `.env.local.secret` に変更が入っているので、
"To reproduce"(再現手順)に復号の手順が書いてないのはおかしいかと。
また、PRのタイトルは何らかのルールを設けた方がいいですね。
よくわからなければ元のIssueと同名 `feat: prepare logging tools` とするのが良いと思います。
（適当にしておくと一覧表示した時に「このPRって何を解決したの？」となるので）

あと、 `.github` ディレクトリに変なファイル混じってますよ。

2023-02-27 08:18 UTC, shin-sforzando requested changes
5点あります。重要度が高いものから順に。

(1) `npm run dev` 、つまりローカルで実行した際のログがLoglareに記録されていません。

(2) PRの"To Reproduce"の日本語がおかしい

> npm run reveal

をして、何をさせたいのか。何が起こっていれば正解なのか。

> https://logflare.app/sources/25487

が何なのか。アクセスさせたいなら、そう書く。

> buildログが生成されている

どこに？誰が？

> https://www.shiftmaking.com/にログが記録されている

「に」は記録されてないですよね。shiftmakingってログ保存機能ついてませんよね。
「の」なら意味がわかります。

> https://shiftmaking-36clxwh6k-mpedia.vercel.app/testpageにログが記録されている

同上。「に」は記録されてないですよね。
「の」なら意味がわかります。

(3) 依存しているライブラリがだいぶ古くなっているようです。

```
@testing-library/react              ^13.4.0  →  ^14.0.0
 @types/node                        18.11.17  →  18.14.2
 @types/react                        18.0.26  →  18.0.28
 @typescript-eslint/eslint-plugin    ^5.46.1  →  ^5.53.0
 @typescript-eslint/parser           ^5.46.1  →  ^5.53.0
 @vitejs/plugin-react                 ^3.0.0  →   ^3.1.0
 @vitest/coverage-c8                 ^0.25.8  →  ^0.29.1
 eslint-config-next                   13.0.7  →   13.2.1
 eslint-config-prettier               ^8.5.0  →   ^8.6.0
 husky                                ^8.0.2  →   ^8.0.3
 jsdom                               ^20.0.3  →  ^21.1.0
 lint-staged                         ^13.1.0  →  ^13.1.2
 next                                 13.0.7  →   13.2.1
 prettier                             ^2.8.1  →   ^2.8.4
 stylelint                          ^14.16.0  →  ^15.2.0
 stylelint-config-prettier            ^9.0.4  →   ^9.0.5
 stylelint-config-recess-order        ^3.0.0  →   ^4.0.0
 stylelint-config-recommended-scss    ^8.0.0  →   ^9.0.1
 typescript                            4.9.4  →    4.9.5
 vite-tsconfig-paths                  ^4.0.3  →   ^4.0.5
 vitest                              ^0.25.8  →  ^0.29.1
 vitest-github-actions-reporter       ^0.9.0  →  ^0.10.0
```

これらの更新について更新方針は定まっていますか。

(4) `.env.local` を使ってる様子がありません。
不要なら削除した方が良いのでは。

(5) `favicon.ico` を消していますが、ではいつか `favicon.ico` を設定するIssueが必要なのでは。

2023-02-28 00:42 UTC, yktt-nuane commented
依存ライブラリの更新方針に関しては、別途相談させて頂きたいです。

2023-02-28 04:59 UTC, shin-sforzando requested changes

2023-02-28 04:59 UTC, shin-sforzando commented on src/logger/logger.js
> +export default logger
このloggerを使った処理がどこにも見当たりませんでした。送信が試せていないのでは？

2023-02-28 04:59 UTC, shin-sforzando commented on package.json
> +    "pino-logflare": "^0.3.12",
ログの送信は動作に必要なものなので、 `devDependencies` ではなく `dependencies` に記載されるべきですね。

2023-02-28 04:59 UTC, shin-sforzando commented on src/logger/logger.js
> +
なんでこのファイルだけjsなんですか？

2023-02-28 04:59 UTC, shin-sforzando commented on README.md
> +LOGFLARE_SOURCE_TOKEN=****************
ご存知の通り、 `.env.local` はLocalの動作で使われる環境変数ですし、GItから無視されてますよね。
では本番環境ではこれらの値をどう読み込んでますか？

2023-02-28 05:00 UTC, shin-sforzando commented
再掲。
favicon.ico を消していますが、ではいつか favicon.ico を設定するIssueが必要なのでは。

2023-02-28 05:42 UTC, yktt-nuane commented on README.md
> +LOGFLARE_SOURCE_TOKEN=****************
vercelから読み込ませているので、Detail of the changeに追記しました。

2023-02-28 06:30 UTC, yktt-nuane commented
> 再掲。 favicon.ico を消していますが、ではいつか favicon.ico を設定するIssueが必要なのでは。

まだ調査中で、ドキュメントを見つけられていませんが、Next.13のベータ版はfavicon.icoが自動生成されなくなっており、favicon.icoファイルがなくても、自動的にfaviconが生成されるようになっています。
もし、僕の認識が間違いでしたら、favicon.icoを設定するissueを作ります。

2023-02-28 06:34 UTC, shin-sforzando commented
> Next.13のベータ版はfavicon.icoが自動生成されなくなっており、favicon.icoファイルがなくても、自動的にfaviconが生成されるようになっています。

んんん？日本語がおかしい。自動作成されるのされないのどっち？？？

2023-02-28 06:42 UTC, yktt-nuane commented
> > Next.13のベータ版はfavicon.icoが自動生成されなくなっており、favicon.icoファイルがなくても、自動的にfaviconが生成されるようになっています。
> 
> んんん？日本語がおかしい。自動作成されるのされないのどっち？？？

favicon.icoが自動生成されないです。

2023-02-28 06:52 UTC, shin-sforzando commented
> favicon.icoが自動生成されないです。

うん、だからfavicon.icoを設定するIssueが必要ですよね、って話なんですけど。

2023-02-28 06:56 UTC, shin-sforzando commented
![Screenshot 2023-02-28 at 15 55 15](https://user-images.githubusercontent.com/32637762/221777344-9c573442-06ac-47fb-9952-58f41beccfb1.png)
実際なくなってるようですし。

2023-03-02 09:35 UTC, shin-sforzando reviewed
まず、修正方針について合意取りたいです。
そもそも論なので「そもそも」という言葉をいっぱい使います。

そもそもUnit TestやCI上でのログをLogflareで見たいんですか？って話で。
「すべてのログが集約される」と言うゴールに真面目に取り組まれたとは思うんですが、
そもそも何故「すべてのログが集約されてて欲しいの？」に立ち返ると、不具合が生じたときに調査をしやすくするため、ってのはありますよね。
で、Unit Testが通らなかった、って不具合はシステムの不具合とも言えるけど、実質的にはテストの不具合なので、Vitestが標準出力するログを見る方が良いし（現状はVitestが動くだけでVitestのログがLogflareには飛んでないようですが）、テストはコミット時や書き換え時に気軽に走らせたいもので（例えば `vitest watch` しながらリファクタリングとかしてたら膨大なログが生まれる事になる）、他の人に常に見せたいものでもない。

GitHub Actionsについても、GitHub Actions上でbuildした後、基本的にすぐVercel上でBuildされて同じようなログが流れるわけで、
仮にGitHub Actions上でエラーだけどVercelではノーエラー、またはその逆みたいな現象が生じたとしても、大事なのはVercel側なのは揺るがないし、
ほぼ同じタイミングで同じコマンドのログを流しても、単に量増やしてるだけで意味はない、というか見にくくなって逆効果ですよね。

> もっと上位で定義すれば何回も定義しなくても良くできますね。（技術的には）

とコメントつけました。
それ以外にも `.env.test.local` の準備の仕方など、技術的にはあってますけど、
「そもそもIssue#7のゴールって何？どこを目指してるの？」が考慮不十分に感じます。
「とにかく全部のログがLogflareにある状態にするんだ、そうすればログの探索先で迷うことがなくなる！」っていうのもアリとは思いますが、だとしたらVitestのログが飛んでないのでRequestChangeになりますし、
「調査に必要なログが適切にLogflareにある状態にして調査効率を上げるんだ！」なら、余計なログが混入している上に動作させるためだけに余計な秘匿ファイル増やしてるのでRequestChangeになります。

2023-03-02 09:35 UTC, shin-sforzando commented on .github/workflows/ci.yml
> +          LOGFLARE_SOURCE_ID: ${{ secrets.LOGFLARE_SOURCE_ID }}
もっと上位で定義すれば何回も定義しなくても良くできますね。（技術的には）

2023-03-02 09:41 UTC, shin-sforzando commented
再々掲。

https://github.com/yktt-nuane/shiftmaking/pull/53#issuecomment-1447672897

Issue作成は何よりも優先してください。
作業に集中してIssue忘れた、やらなきゃいけないことが漏れた、完成したと思ったら完成してなかった、って最悪ですし、
作業は自分だけの話ですが、Issueはみんなものなので。

2023-03-05 10:36 UTC, yktt-nuane commented
[pinoとpino-logflareをdependenciesに移動して、installし直し](https://github.com/yktt-nuane/shiftmaking/pull/53/commits/5485f94adfac5ce76d953f92a2c7be8a30959d69)に戻りました。
Vitest実行時にLogflareの処理をskipする方針で修正していきます。

2023-03-08 07:16 UTC, shin-sforzando requested changes

2023-03-08 07:16 UTC, shin-sforzando commented on src/app/page.tsx
> +import logger from '@/logger/logger'
【余談】せっかく用意した `logger` を使わずに `console.log` とかしちゃうヒューマンエラーはよくある話で、
Tipsとして Console.logをオリジナルロガーで上書きしておく、みたいな手もありますけどね。
第一級関数言語だからできる技ですが。

2023-03-09 01:40 UTC, yktt-nuane commented on src/logger/logger.ts
> +if (process.env.NODE_ENV === 'test' || process.env.GITHUB_ACTIONS === 'true') {
> CI で判定した方がいいですね。たいていのCIツールはこの環境変数がセットされているのでGitHub Actionsじゃないところに持っていても書き換えなくて済みます。

testに関しては、このままでいいですか？Localでnpm run test:unitを実行すると、判定が効かなくなりそうですが。

2023-03-10 05:33 UTC, shin-sforzando requested changes

2023-03-10 05:33 UTC, shin-sforzando commented on src/logger/logger.ts
> +      write: () => {
https://github.com/pinojs/pino/blob/master/pino.d.ts#L415-L426 って読んでます？

`write()` が定義されてれば勝手に `asObject: true` になると書いているので、今の書き方は冗長ですし、
`write()` が定義されてなければ勝手に `console` にフォールバックするって書いてますから、
ここは `asObject: true` だけ定義するのが良いのでは？

2023-03-10 05:33 UTC, shin-sforzando commented on src/logger/logger.ts
> +    },
プログラミングも"言語"なので、文意を考えた方が良くて、
「ある条件によって設定を切り替えている」のと「ある条件によって、ロガーを二つ（PinoとPinoじゃない何か）切り替えている」で言うと、前者ですよね。
だったら、書ける限り前者的に書いた方がいいです。

2023-03-10 07:56 UTC, yktt-nuane commented on src/logger/logger.ts
> +if (process.env.NODE_ENV != undefined || process.env.CI != undefined) {
問題ないと思ってcommitしたのですが、CIでエラーになりました。

2023-03-11 11:56 UTC, yktt-nuane commented on src/logger/logger.ts
> +if (process.env.NODE_ENV != undefined || process.env.CI != undefined) {
`if (process.env.NODE_ENV == "test" || !!process.env.CI) {`
に変更致しました。

2023-03-11 13:28 UTC, shin-sforzando approved these changes

2023-03-11 13:28 UTC, merged